name:                hmatrix-backprop
version:             0.1.0.0
github:              "mstksg/hmatrix-backprop"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            hmatrix operations lifted for backprop
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
    hmatrix operations lifted for backprop.

    Meant to act as a drop-in replacement to the API of
    Numeric.LinearAlgebra.Static.  Just change your imports, and your
    functions are automatically backpropagatable.

    See README on Github at <https://github.com/mstksg/hmatrix-backprop#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

dependencies:
- backprop >= 0.1.2
- base >= 4.7 && < 5
- hmatrix >= 0.18
- hmatrix-vector-sized >= 0.1
- microlens
- vector-sized >= 0.6

library:
  source-dirs: src
  exposed-modules:
  - Numeric.LinearAlgebra.Static.Backprop
  dependencies:
  - ANum >= 0.2
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - vector

tests:
  hmatrix-backprop-test:
    main:                Spec.hs
    other-modules:
    - Nudge
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix-backprop
    - hedgehog
    - finite-typelits
    - microlens-platform
