name:                hmatrix-backprop
version:             0.1.0.0
github:              "mstksg/hmatrix-backprop"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            hmatrix operations lifted for backprop
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mstksg/hmatrix-backprop#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- hmatrix >= 0.18.1
- backprop >= 0.1.2
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- microlens
- vector
- vector-sized

library:
  source-dirs: src
  exposed-modules:
  - Numeric.LinearAlgebra.Static.Backprop
  ghc-options:
  - -fwarn-redundant-constraints

tests:
  hmatrix-backprop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmatrix-backprop
    - hedgehog
    - finite-typelits
    - microlens-platform
